// Mock data for development - will be replaced with real API calls

import type { Enquiry } from '../types/enquiry.types'
import type { Blog } from '../types/blog.types'
import type { Career } from '../types/career.types'
import type { Applicant } from '../types/applicant.types'
import type { Gallery } from '../types/gallery.types'
import type { CaseStudy } from '../types/case-study.types'
import type { DashboardStats, DashboardAnalytics } from '../types/dashboard.types'

export const mockEnquiries: Enquiry[] = [
  {
    id: 1,
    full_name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '+1 234 567 8900',
    company_name: 'Acme Corporation',
    service_type: 'consulting',
    subject: 'Project Inquiry - New Construction',
    description: 'We are looking for engineering consultation for our new office building project.',
    enquiry_date: '2024-01-15T10:30:00Z',
    assigned_to: { id: 5, first_name: 'Jane', last_name: 'Doe' },
    status: 'new',
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-01-15T10:30:00Z',
  },
  {
    id: 2,
    full_name: 'Sarah Johnson',
    email: 'sarah.j@techcorp.com',
    phone: '+1 345 678 9012',
    company_name: 'TechCorp Industries',
    service_type: 'engineering',
    subject: 'Structural Engineering Services',
    description: 'Need structural engineering services for manufacturing facility expansion.',
    enquiry_date: '2024-01-14T14:20:00Z',
    assigned_to: { id: 3, first_name: 'Mike', last_name: 'Wilson' },
    status: 'start_working',
    created_at: '2024-01-14T14:20:00Z',
    updated_at: '2024-01-16T09:15:00Z',
  },
  {
    id: 3,
    full_name: 'Michael Brown',
    email: 'm.brown@buildings.com',
    phone: '+1 456 789 0123',
    company_name: 'Buildings LLC',
    service_type: 'construction',
    subject: 'Construction Project Quote',
    description: 'Requesting quote for commercial construction project.',
    enquiry_date: '2024-01-13T11:45:00Z',
    status: 'on_hold',
    hold_reason: 'Waiting for client to provide detailed specifications',
    created_at: '2024-01-13T11:45:00Z',
    updated_at: '2024-01-15T16:30:00Z',
  },
]

export const mockBlogs: Blog[] = [
  {
    id: 1,
    blog_title: 'Sustainable Engineering Practices for 2024',
    slug: 'sustainable-engineering-practices-2024',
    category: 'Engineering',
    featured_image: '/uploads/blog/engineering1.jpg',
    short_description: 'Explore the latest sustainable engineering practices that are shaping the industry.',
    blog_content: '<p>Detailed content about sustainable engineering practices...</p>',
    author: 'John Doe',
    tags: 'engineering, sustainability, green-building',
    meta_title: 'Sustainable Engineering Practices 2024',
    meta_description: 'Learn about sustainable engineering practices',
    status: 'published',
    is_featured: true,
    publish_date: '2024-01-10T08:00:00Z',
    views: 1250,
    created_at: '2024-01-10T08:00:00Z',
    updated_at: '2024-01-10T08:00:00Z',
  },
  {
    id: 2,
    blog_title: 'Modern Construction Techniques',
    slug: 'modern-construction-techniques',
    category: 'Construction',
    featured_image: '/uploads/blog/construction1.jpg',
    short_description: 'Discover cutting-edge construction techniques improving efficiency.',
    blog_content: '<p>Content about modern construction techniques...</p>',
    author: 'Jane Smith',
    tags: 'construction, technology, innovation',
    status: 'published',
    is_featured: false,
    publish_date: '2024-01-08T10:00:00Z',
    views: 890,
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-01-08T10:00:00Z',
  },
]

export const mockCareers: Career[] = [
  {
    id: 1,
    job_code: 'ENG-001',
    job_title: 'Senior Structural Engineer',
    department: 'Engineering',
    role_category: 'Technical',
    industry_type: 'Construction',
    employment_type: 'full_time',
    work_mode: 'on_site',
    location: 'New York, NY',
    number_of_openings: 2,
    experience_required: '5-8 years',
    education_qualification: 'Bachelor\'s in Civil Engineering',
    key_skills: 'AutoCAD, Structural Analysis, Project Management',
    description: 'Lead structural engineering projects and mentor junior engineers.',
    roles_and_responsibilities: 'Design structural systems, review drawings, coordinate with architects',
    benefits: 'Health insurance, 401k, paid time off',
    application_deadline: '2024-03-15',
    status: 'open',
    posted_date: '2024-01-05T09:00:00Z',
    created_at: '2024-01-05T09:00:00Z',
    updated_at: '2024-01-05T09:00:00Z',
  },
  {
    id: 2,
    job_code: 'ENG-002',
    job_title: 'Project Manager',
    department: 'Operations',
    role_category: 'Management',
    industry_type: 'Construction',
    employment_type: 'full_time',
    work_mode: 'hybrid',
    location: 'Chicago, IL',
    number_of_openings: 1,
    experience_required: '8-10 years',
    education_qualification: 'Bachelor\'s in Construction Management',
    key_skills: 'PMP, MS Project, Team Leadership',
    description: 'Manage large-scale construction projects from inception to completion.',
    roles_and_responsibilities: 'Project planning, budget management, stakeholder coordination',
    benefits: 'Health insurance, bonus, company car',
    application_deadline: '2024-02-28',
    status: 'open',
    posted_date: '2024-01-03T10:00:00Z',
    created_at: '2024-01-03T10:00:00Z',
    updated_at: '2024-01-03T10:00:00Z',
  },
]

export const mockApplicants: Applicant[] = [
  {
    id: 1,
    career_id: 1,
    career: { id: 1, job_title: 'Senior Structural Engineer', job_code: 'ENG-001' },
    applicant_name: 'Robert Chen',
    mobile: '+1 555 123 4567',
    email: 'r.chen@email.com',
    applied_date: '2024-01-12T14:30:00Z',
    current_location: 'San Francisco, CA',
    experience: '6 years',
    current_company: 'BuildRight Engineering',
    current_ctc: 95000,
    expected_ctc: 110000,
    notice_period: '30 days',
    resume_path: '/uploads/applicants/resume1.pdf',
    status: 'under_review',
    created_at: '2024-01-12T14:30:00Z',
    updated_at: '2024-01-14T11:00:00Z',
  },
  {
    id: 2,
    career_id: 1,
    career: { id: 1, job_title: 'Senior Structural Engineer', job_code: 'ENG-001' },
    applicant_name: 'Emily Davis',
    mobile: '+1 555 987 6543',
    email: 'emily.d@email.com',
    applied_date: '2024-01-11T09:15:00Z',
    current_location: 'Boston, MA',
    experience: '7 years',
    current_company: 'Structural Solutions Inc',
    current_ctc: 105000,
    expected_ctc: 125000,
    notice_period: '45 days',
    resume_path: '/uploads/applicants/resume2.pdf',
    status: 'shortlisted',
    interview_date: '2024-01-20T15:00:00Z',
    created_at: '2024-01-11T09:15:00Z',
    updated_at: '2024-01-15T10:30:00Z',
  },
]

export const mockGallery: Gallery[] = [
  {
    id: 1,
    gallery_title: 'Commercial Projects 2024',
    category: 'Commercial',
    description: 'Showcase of our commercial construction projects',
    status: 'active',
    images: [
      { id: 1, gallery_id: 1, image_path: '/uploads/gallery/img1.jpg', image_title: 'Office Tower', alt_text: 'Modern office tower', display_order: 0, created_at: '2024-01-01T00:00:00Z' },
      { id: 2, gallery_id: 1, image_path: '/uploads/gallery/img2.jpg', image_title: 'Shopping Mall', alt_text: 'Shopping complex', display_order: 1, created_at: '2024-01-01T00:00:00Z' },
      { id: 3, gallery_id: 1, image_path: '/uploads/gallery/img3.jpg', image_title: 'Hotel Complex', alt_text: 'Luxury hotel', display_order: 2, created_at: '2024-01-01T00:00:00Z' },
    ],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    gallery_title: 'Residential Projects',
    category: 'Residential',
    description: 'Our residential construction portfolio',
    status: 'active',
    images: [
      { id: 4, gallery_id: 2, image_path: '/uploads/gallery/img4.jpg', image_title: 'Luxury Villa', alt_text: 'Modern villa', display_order: 0, created_at: '2024-01-02T00:00:00Z' },
    ],
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
  },
]

export const mockCaseStudies: CaseStudy[] = [
  {
    id: 1,
    case_study_title: 'Downtown Office Complex',
    slug: 'downtown-office-complex',
    client_name: 'Metro Developers',
    service_type: 'construction',
    industry: 'Real Estate',
    featured_image: '/uploads/case-study/case1.jpg',
    short_description: 'Complete construction of 20-story office complex',
    challenge: 'Tight timeline in urban environment with limited space',
    solution: 'Modular construction approach with phased delivery',
    impact: 'Completed 2 months ahead of schedule, 15% under budget',
    technologies_used: 'BIM, Prefabrication, IoT sensors',
    project_duration: '18 months',
    status: 'published',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    case_study_title: 'Industrial Plant Expansion',
    slug: 'industrial-plant-expansion',
    client_name: 'Manufacturing Corp',
    service_type: 'engineering',
    industry: 'Manufacturing',
    featured_image: '/uploads/case-study/case2.jpg',
    short_description: 'Engineering and construction of manufacturing facility expansion',
    challenge: 'Maintaining operations during expansion',
    solution: 'Phased construction with temporary production lines',
    impact: '50% increase in production capacity',
    technologies_used: 'Automation, Lean Manufacturing',
    project_duration: '12 months',
    status: 'published',
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
  },
]

export const mockDashboardStats: DashboardStats = {
  total_enquiries: 150,
  total_applications: 75,
  total_blogs: 30,
  active_careers: 12,
  case_studies: 15,
  gallery_count: 8,
  new_enquiries_today: 5,
}

export const mockDashboardAnalytics: DashboardAnalytics = {
  enquiries_trend: [
    { month: 'Jan', count: 45 },
    { month: 'Feb', count: 52 },
    { month: 'Mar', count: 38 },
    { month: 'Apr', count: 65 },
    { month: 'May', count: 48 },
    { month: 'Jun', count: 72 },
    { month: 'Jul', count: 55 },
    { month: 'Aug', count: 60 },
    { month: 'Sep', count: 43 },
    { month: 'Oct', count: 58 },
    { month: 'Nov', count: 67 },
    { month: 'Dec', count: 75 },
  ],
}
